apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter
  labels:
    app: converter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: converter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8
  template:
    metadata:
      labels:
        app: converter
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: pool-1
      containers:
        - name: converter
          image: shrechan/converter:latest
          envFrom:
            - configMapRef:
                name: converter-configmap
            - secretRef:
                name: converter-secret
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"