apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: video-converter-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: video-converter
  updatePolicy:
    updateMode: "Auto"  # Automatically adjusts resources
